properties:
  - type: secure
    name: apikey
    value: ${API_KEY}
  - type: string
    name: location
    value: "us"
  - type: string
    name: scope_id
    value: "scope_id"
  - type: string
    name: profile_id
    value: "profile_id"
  - type: string
    name: group_profile_id
    value: "group_profile_id"
triggers:
  - type: manual
    name: Manual Trigger - 0
    eventListener: manual-trigger-listener
inputs:
  - type: git
    path: .tekton
    branch: main
    service: ${scc-tekton-playground}
  - type: git
    path: tasks
    branch: main
    service: ${scc-tekton-playground}