---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: manual-template
spec:
  params:
    - name: location
      description: Endpoint location for the SCC api.  Values are "us" or "eu".
    - name: account_id
      description: IBM Cloud account ID.
    - name: scope_id
      description: The unique ID of the scope.
    - name: profile_id
      description: The unique ID of the profile.
    - name: group_profile_id
      description: The ID of the profile group.
    - name: apikey
      description: IBM Cloud API Key.
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: ci-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: location
            value: $(params.location)
          - name: account_id
            value: $(params.account_id)
          - name: scope_id
            value: $(params.scope_id)
          - name: profile_id
            value: $(params.profile_id)
          - name: group_profile_id
            value: $(params.group_profile_id)
          - name: apikey
            value: $(params.apikey)

