---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  params:
    - name: location
      description: Endpoint location for the SCC api.  Values are "us" or "eu".
    - name: scope_id
      description: The unique ID of the scope.
    - name: profile_id
      description: The unique ID of the profile.
    - name: group_profile_id
      description: The ID of the profile group.
    - name: apikey
      description: IBM Cloud API Key.

  tasks:

    - name: scc-initiator
      taskRef:
        name: scc-initiator
      params:
        - name: location
          value: $(params.location)
        - name: scope_id
          value: $(params.scope_id)
        - name: profile_id
          value: $(params.profile_id)
        - name: group_profile_id
          value: $(params.group_profile_id)
        - name: apikey
          value: $(params.apikey)
